name: bloc_provider_package
description: "A package for managing state using BlocProvider and MultiBlocProvider."
version: 0.0.1+1
homepage: https://github.com/trongtinh7727/bloc_provider

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nested: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
